(() => {
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let timer;
  async function render(target,{data,save,toast}) {
    clearTimeout(timer);target.innerHTML='<h3>Offline intelligence</h3><p class="muted">Checking the local model service…</p>';
    let state;try{state=await lumenConnection.request('offline/status',{})}catch(e){if(target.isConnected)target.innerHTML=`<h3>Offline intelligence</h3><p class="runtime-error">${esc(e.message)}</p>`;return}
    if(!target.isConnected)return;
    const installed=new Set((state.models||[]).map(m=>typeof m==='string'?m:m.name));
    target.innerHTML=`<h3>Offline intelligence</h3><p class="muted">Optional models run on this device. Your text stays local when Offline is selected; voice still uses Gemini.</p><p class="notice">${state.available?'Ollama is connected. Small models fit the 8 GB design target; available memory and speed vary.':'Start Ollama on this device to enable local models. Lumen never switches an offline conversation to the cloud.'} <a href="https://ollama.com/download" target="_blank" rel="noopener noreferrer">Get Ollama ↗</a> · <button id="offline-refresh">Refresh</button>${state.bundled&&!state.available?' <button id="offline-start">Start local engine</button>':''}</p><div id="offline-catalog">${(state.catalog||[]).map(m=>`<article class="model-card"><div><h3>${esc(m.name||m.id)}</h3><p>${esc(m.description||'Small local language model')} · ${esc(m.size||m.downloadSize||'See download progress for size')}</p><span class="badge">${installed.has(m.id)?'Installed':'Optional download'}</span>${m.source?` <a href="${esc(m.source)}" target="_blank" rel="noopener noreferrer">Model &amp; license ↗</a>`:''}</div><button data-pull="${esc(m.id)}" ${!state.available||installed.has(m.id)?'disabled':''}>${installed.has(m.id)?'Installed':'Download model'}</button></article>`).join('')}</div><div id="offline-downloads"></div><label style="margin-top:18px">Offline conversation model<select id="offline-model"><option value="">Select an installed model</option>${(state.catalog||[]).filter(m=>installed.has(m.id)).map(m=>`<option value="${esc(m.id)}">${esc(m.name||m.id)}</option>`).join('')}</select></label><button id="offline-select" style="margin-top:12px">Use this offline model</button><p class="runtime-note">Model downloads can use several GB of disk space and network data. No model downloads automatically.</p>`;
    target.querySelector('#offline-refresh').onclick=()=>render(target,{data,save,toast});
    const starter=target.querySelector('#offline-start');if(starter)starter.onclick=async()=>{starter.disabled=true;try{await lumenConnection.request('offline/start',{});await render(target,{data,save,toast})}catch(e){toast(e.message);starter.disabled=false}};
    const select=target.querySelector('#offline-model');select.value=data.offlineModel||'';
    target.querySelector('#offline-select').onclick=()=>{if(!select.value){toast('Download and select a local model first.');return}data.offlineModel=select.value;data.provider='Offline';save();const pref=document.querySelector('#provider-preference');if(pref)pref.value='Offline';window.dispatchEvent(new Event('lumen-connection'));toast('Offline model selected. Text stays on this device.')};
    target.querySelectorAll('[data-pull]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await lumenConnection.request('offline/pull',{model:b.dataset.pull});toast('Download started. You can keep using Lumen.');poll()}catch(e){toast(e.message);b.disabled=false}});
    async function poll(){clearTimeout(timer);if(!target.isConnected)return;try{const result=await lumenConnection.request('offline/downloads',{});if(!target.isConnected)return;const jobs=result.downloads||[];if(jobs.some(j=>j.status==='completed'&&!installed.has(j.model))){await render(target,{data,save,toast});return}target.querySelector('#offline-downloads').innerHTML=jobs.map(j=>`<article class="model-card"><div><h3>${esc(j.model)}</h3><p>${esc(j.status)}${j.detail?' · '+esc(j.detail):j.message?' · '+esc(j.message):''}${j.error?' · '+esc(j.error):''}</p>${j.total?`<progress max="${Number(j.total)}" value="${Number(j.completed||0)}" aria-label="Model download progress"></progress>`:''}</div>${['running','downloading','pulling','queued'].includes(j.status)?`<button data-cancel-download="${esc(j.id)}">Cancel download</button>`:''}</article>`).join('');target.querySelectorAll('[data-cancel-download]').forEach(b=>b.onclick=async()=>{try{await lumenConnection.request('offline/cancel',{id:b.dataset.cancelDownload});poll()}catch(e){toast(e.message)}});for(const b of target.querySelectorAll('[data-pull]'))b.disabled=!state.available||installed.has(b.dataset.pull)||jobs.some(j=>['queued','downloading','running'].includes(j.status));if(jobs.some(j=>['running','downloading','pulling','queued'].includes(j.status)))timer=setTimeout(poll,1400)}catch(e){toast(e.message)}}
    poll();
  }
  window.lumenOfflineUI={render};
})();
