(() => {
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=(route,input={})=>lumenConnection.request(route,input);
  const stamp=v=>v?new Date(v).toLocaleString():'Not scheduled';
  const bytes=v=>Number.isFinite(v)?(v/1024**3).toFixed(1)+' GB':'Unavailable';
  let snapshot={agents:[],routines:[],jobs:[],settings:{}},timer,context,root,current;
  const permissions=[['system.read','Read system status','CPU, memory, uptime and platform details.'],['workspace.read','Read workspace notes','Text files inside the dedicated Lumen workspace may be sent to this agent’s provider.'],['gmail.read','Read Gmail','Unread message sender, subject, date, and text excerpts may be sent to this agent’s provider.'],['notes.write','Save new notes','Save the task’s result as a new workspace note. Existing files stay intact.']];
  const providerNames={codex:'ChatGPT Account',openai:'OpenAI API','claude-account':'Claude Account',claude:'Claude API'};
  const replyLimit=2400,priorResultLimit=5000;
  const providerName=value=>providerNames[value]||value;
  function permissionName(p){return permissions.find(x=>x[0]===p)?.[1]||p}
  function header(eyebrow,title,description,buttons=''){return `<div class="page-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p class="muted">${description}</p></div>${buttons}</div>`}
  async function action(fn){try{return await fn()}catch(e){context.toast(e.message);return null}}
  async function reload(){snapshot=await api('runtime/state');return snapshot}
  function closeDialog(){document.querySelector('#runtime-editor')?.remove()}
  function dialog(title,content,onSubmit){closeDialog();const d=document.createElement('dialog');d.id='runtime-editor';d.className='runtime-dialog';d.innerHTML=`<form class="runtime-form"><div class="dialog-heading"><h2>${title}</h2><button type="button" data-close aria-label="Close dialog">×</button></div>${content}<p class="runtime-error" role="status" data-error></p><div class="dialog-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">Save</button></div></form>`;document.body.append(d);d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.onclose=()=>d.remove();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=d.querySelector('[type=submit]');b.disabled=true;try{await onSubmit(e.target);d.close();if(root?.isConnected)await render(current,root,context)}catch(err){d.querySelector('[data-error]').textContent=err.message}finally{b.disabled=false}};d.showModal();return d}
  function editAgent(id){const a=snapshot.agents.find(a=>a.id===id)||{provider:'codex',permissions:[]};dialog(id?'Edit agent':'New agent',`<label>Name<input name="name" required maxlength="60" value="${esc(a.name)}"></label><label>Purpose and instructions<textarea name="instructions" rows="4" required maxlength="1000">${esc(a.instructions)}</textarea></label><label>Text provider<select name="provider"><option value="codex">ChatGPT Account</option><option value="openai">OpenAI API</option><option value="claude-account">Claude Account</option><option value="claude">Claude API</option></select></label><fieldset><legend>Access during a task</legend>${permissions.map(([id,name,description])=>`<label class="permission"><input type="checkbox" name="permissions" value="${id}" ${a.permissions.includes(id)?'checked':''}><span>${name}<small>${description}</small></span></label>`).join('')}</fieldset><p class="runtime-note">Only the access you select is used. Tasks cannot execute shell commands, delete files, or contact people.</p>`,async f=>{await api('agent/save',{...a,name:f.elements.name.value.trim(),instructions:f.elements.instructions.value.trim(),provider:f.elements.provider.value,permissions:[...f.querySelectorAll('[name=permissions]:checked')].map(x=>x.value)});context.toast('Agent saved on this device.')}).querySelector('[name=provider]').value=a.provider;}
  function editRoutine(id){
    if(!snapshot.agents.length){context.toast('Create an agent first.');return}
    const r=snapshot.routines.find(r=>r.id===id)||{agentId:snapshot.agents[0].id,enabled:false,schedule:{type:'daily',time:'09:00'}};
    const options=snapshot.agents.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} · ${esc(providerName(a.provider))}</option>`).join('');
    const d=dialog(id?'Edit automation':'New automation',`<label>Agent for this automation<select name="agentId" aria-label="Agent for this automation">${options}</select><small>The selected agent controls the AI provider, instructions, and access used by this task.</small></label><label>Name<input name="name" maxlength="60" required value="${esc(r.name)}"></label><label>Task<textarea name="prompt" rows="4" maxlength="8000" required>${esc(r.prompt)}</textarea></label><div class="form-columns"><label>Repeat<select name="scheduleType"><option value="daily">Daily</option><option value="interval">Every N minutes</option></select></label><label data-time>Local time<input type="time" name="time" value="${esc(r.schedule.time||'09:00')}"></label><label data-interval hidden>Minutes<input type="number" name="minutes" min="15" max="10080" value="${Number(r.schedule.minutes||60)}"></label></div><label class="permission"><input name="enabled" type="checkbox" ${r.enabled?'checked':''}><span>Enable this automation<small>Runs only while the scheduler and Lumen service are on. The selected agent’s provider must be connected.</small></span></label>`,async f=>{await api('routine/save',{...r,name:f.elements.name.value.trim(),agentId:f.elements.agentId.value,prompt:f.elements.prompt.value.trim(),enabled:f.elements.enabled.checked,schedule:f.elements.scheduleType.value==='daily'?{type:'daily',time:f.elements.time.value}:{type:'interval',minutes:Number(f.elements.minutes.value)}});context.toast('Automation saved.')});
    d.querySelector('[name=agentId]').value=r.agentId;
    const select=d.querySelector('[name=scheduleType]');
    select.value=r.schedule.type;
    select.onchange=()=>{d.querySelector('[data-time]').hidden=select.value!=='daily';d.querySelector('[data-interval]').hidden=select.value!=='interval'};
    select.onchange();
  }
  function runTask(agentId){const a=snapshot.agents.find(x=>x.id===agentId);const d=dialog('Give '+esc(a.name)+' a task',`<label>What should this agent do?<textarea name="prompt" rows="5" maxlength="8000" required placeholder="For example: review my workspace notes and draft a plan for today."></textarea></label><p class="notice">Provider: ${esc(a.provider)} · Access: ${a.permissions.length?a.permissions.map(permissionName).map(esc).join(', '):'Conversation only'}</p>`,async f=>{await api('job/run',{agentId,prompt:f.elements.prompt.value.trim()});context.toast('Task started. Its result will appear in Activity.')});d.querySelector('[type=submit]').textContent='Run task';}
  function jobsHTML(){return `<h3 style="margin-top:30px">Activity</h3>${snapshot.jobs.length?snapshot.jobs.slice(0,20).map(j=>{const agent=snapshot.agents.find(a=>a.id===j.agentId),agentName=j.name||j.agentName||agent?.name||'Agent task';return `<article class="job"><header><h3>${['running','queued'].includes(j.status)?'<span class="running-dot"></span>':''}${esc(agentName)}</h3><span class="badge">${esc(j.status)}</span>${['running','queued'].includes(j.status)?`<button data-stop-job="${esc(j.id)}">Stop task</button>`:''}</header><p>${esc(stamp(j.createdAt))} · ${esc(providerName(j.provider))}${j.notePath?' · Saved: '+esc(j.notePath):''}</p>${j.prompt?`<p>${esc(j.prompt.slice(0,250))}</p>`:''}${j.error?`<p class="runtime-error">${esc(j.error)}</p>`:''}${j.output?`<details><summary>Read result</summary><div class="runtime-result">${esc(j.output)}</div><form class="job-reply" data-reply-job="${esc(j.id)}"><label for="reply-${esc(j.id)}">Reply to ${esc(agentName)}</label><textarea id="reply-${esc(j.id)}" rows="3" maxlength="${replyLimit}" required placeholder="Ask a follow-up or tell this agent what to do next."></textarea><div class="job-reply-actions"><small>Uses the same agent, provider, and access permissions.</small><button class="primary" type="submit">Send to agent</button></div><p class="runtime-error" role="status" data-reply-error></p></form></details>`:''}</article>`}).join(''):'<p class="empty">Completed and running tasks appear here.</p>'}`}
  function bindJobs(){
    root.querySelectorAll('[data-stop-job]').forEach(b=>b.onclick=()=>action(async()=>{await api('job/stop',{id:b.dataset.stopJob});await render(current,root,context)}));
    root.querySelectorAll('[data-reply-job]').forEach(form=>form.onsubmit=async e=>{
      e.preventDefault();
      const job=snapshot.jobs.find(j=>j.id===form.dataset.replyJob),reply=form.querySelector('textarea').value.trim(),button=form.querySelector('[type=submit]'),error=form.querySelector('[data-reply-error]');
      if(!job||!reply)return;
      button.disabled=true;error.textContent='';
      const shortened=job.output.length>priorResultLimit,prior=job.output.slice(0,priorResultLimit);
      const prompt=`Follow-up request from the user:\n${reply}\n\nUse the previous result below as context, then carry out the follow-up using only your existing Lumen permissions.\n\n--- PREVIOUS RESULT${shortened?' (SHORTENED)':''} ---\n${prior}\n--- END PREVIOUS RESULT ---`;
      try{
        await api('job/run',job.routineId?{routineId:job.routineId,prompt}:{agentId:job.agentId,prompt});
        context.toast('Follow-up sent to the agent.');
        await render(current,root,context);
      }catch(err){error.textContent=err.message;button.disabled=false}
    });
  }
  function agents(){root.innerHTML=`<div class="page">${header('YOUR PERSONAL TEAM','A little help. A lot of possibility.','Give each agent a purpose and choose what it can access.','<button class="primary" id="new-agent">＋ New agent</button>')}<div class="cards">${snapshot.agents.map(a=>`<article class="card"><div class="card-symbol">✧</div><h3>${esc(a.name)}</h3><p>${esc(a.instructions)}</p><div class="meta"><span class="status-dot"></span>${esc(a.provider)} · ${a.permissions.length+' access grants'}</div><div class="card-actions"><button class="primary" data-run-agent="${esc(a.id)}">Run task</button><button data-chat-agent="${esc(a.id)}">Start chat</button><button data-edit-agent="${esc(a.id)}">Edit</button><button data-delete-agent="${esc(a.id)}" aria-label="Delete ${esc(a.name)}">Delete</button></div></article>`).join('')}</div><p class="notice">Run task uses the access you grant. Start chat uses this agent’s instructions for a conversation. Scheduled tasks keep running while the local Lumen service is on.</p><div id="legacy-agents"></div><div id="runtime-jobs">${jobsHTML()}</div></div>`;const legacy=root.querySelector('#legacy-agents');if(context.legacyAgents?.length&&!context.legacyImported()){legacy.innerHTML='<button id="import-agents">Import earlier browser agents</button>';legacy.querySelector('button').onclick=()=>action(async()=>{for(const a of context.legacyAgents){if(a&&typeof a.name==='string'&&typeof a.instructions==='string')await api('agent/save',{name:a.name,instructions:a.instructions,provider:'openai',permissions:[]})}context.markImported();await render(current,root,context);context.toast('Earlier agents imported with no workspace permissions.')})}root.querySelector('#new-agent').onclick=()=>editAgent();root.querySelectorAll('[data-edit-agent]').forEach(b=>b.onclick=()=>editAgent(b.dataset.editAgent));root.querySelectorAll('[data-run-agent]').forEach(b=>b.onclick=()=>runTask(b.dataset.runAgent));root.querySelectorAll('[data-chat-agent]').forEach(b=>b.onclick=()=>context.startChat(snapshot.agents.find(a=>a.id===b.dataset.chatAgent)));root.querySelectorAll('[data-delete-agent]').forEach(b=>b.onclick=()=>action(async()=>{await api('agent/delete',{id:b.dataset.deleteAgent});await render(current,root,context)}));bindJobs();}
  function scheduleLabel(r){return r.schedule.type==='daily'?'Daily at '+r.schedule.time:'Every '+r.schedule.minutes+' minutes'}
  function routines(){
    const s=snapshot.settings;
    const cards=snapshot.routines.map(r=>{
      const selected=snapshot.agents.find(a=>a.id===r.agentId);
      const options=snapshot.agents.map(a=>`<option value="${esc(a.id)}" ${a.id===r.agentId?'selected':''}>${esc(a.name)} · ${esc(providerName(a.provider))}</option>`).join('');
      return `<article class="routine"><div class="routine-info"><h3>${esc(r.name)}</h3><p>${esc(r.prompt)}</p><label class="routine-agent">Agent for this automation<select data-routine-agent="${esc(r.id)}" aria-label="Agent for ${esc(r.name)}">${options}</select><small>Provider: ${esc(providerName(selected?.provider||'Unknown'))}</small></label><p style="margin-top:8px">${esc(scheduleLabel(r))} · ${r.enabled?'Enabled':'Paused'} · Next: ${esc(stamp(r.nextRunAt))}</p>${r.lastError?`<p class="runtime-error">Last start attempt: ${esc(r.lastError)}</p>`:''}</div><div class="routine-buttons"><button class="switch" role="switch" aria-label="Enable ${esc(r.name)}" aria-checked="${r.enabled}" data-toggle-routine="${esc(r.id)}"></button><button data-run-routine="${esc(r.id)}">Run now</button><button data-edit-routine="${esc(r.id)}">Edit details</button><button data-delete-routine="${esc(r.id)}">Delete</button></div></article>`;
    }).join('');
    root.innerHTML=`<div class="page">${header('MAKE ROOM FOR WHAT MATTERS','Your day, on a gentler rhythm.','Choose an agent for each automation, then decide when it runs.','<button class="primary" id="new-routine">＋ New automation</button>')}<form id="scheduler-form" class="runtime-toolbar"><label class="permission"><input name="enabled" type="checkbox" ${s.schedulerEnabled?'checked':''}><span>Background scheduler</span></label><label>Daily task limit<input name="budget" aria-label="Daily task limit" type="number" min="1" max="100" value="${Number(s.dailyLimit||12)}" style="width:85px"></label><button type="submit">Save scheduler</button></form><p class="notice">${s.schedulerEnabled?'The scheduler is on.':'The scheduler is paused.'} ${Number(snapshot.usage?.count||0)} tasks started today. The limit applies to agent tasks, including manual runs; chat and voice are separate. This is a request limit, not a currency cap. Times follow the service’s local timezone.</p>${cards||'<p class="empty">Create a routine to start building your day.</p>'}<div id="runtime-jobs">${jobsHTML()}</div></div>`;
    root.querySelector('#new-routine').onclick=()=>editRoutine();
    root.querySelector('#scheduler-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('runtime/settings',{schedulerEnabled:e.target.elements.enabled.checked,dailyLimit:Number(e.target.elements.budget.value)});await render(current,root,context);context.toast('Scheduler settings saved.')})};
    root.querySelectorAll('[data-routine-agent]').forEach(select=>select.onchange=()=>action(async()=>{const r=snapshot.routines.find(r=>r.id===select.dataset.routineAgent);await api('routine/save',{...r,agentId:select.value});await render(current,root,context);context.toast('Automation agent updated.')}));
    root.querySelectorAll('[data-edit-routine]').forEach(b=>b.onclick=()=>editRoutine(b.dataset.editRoutine));
    root.querySelectorAll('[data-toggle-routine]').forEach(b=>b.onclick=()=>action(async()=>{const r=snapshot.routines.find(r=>r.id===b.dataset.toggleRoutine);await api('routine/save',{...r,enabled:!r.enabled});await render(current,root,context)}));
    root.querySelectorAll('[data-run-routine]').forEach(b=>b.onclick=()=>action(async()=>{await api('job/run',{routineId:b.dataset.runRoutine});await render(current,root,context);context.toast('Automation started.')}));
    root.querySelectorAll('[data-delete-routine]').forEach(b=>b.onclick=()=>action(async()=>{await api('routine/delete',{id:b.dataset.deleteRoutine});await render(current,root,context)}));
    bindJobs();
  }
  async function files(){const result=await api('workspace/list');if(!root.isConnected||current!=='files')return;root.innerHTML=`<div class="page">${header('YOUR WORKSPACE','A place for your thoughts.','Real notes saved in Lumen’s dedicated workspace.','<button class="primary" id="new-note">＋ New note</button>')}<div class="file-list">${result.files.map(f=>`<button class="file-entry" data-read-file="${esc(f.path||f.name)}"><span>▤ &nbsp; ${esc(f.path||f.name)}</span><small>${Number(f.size||0).toLocaleString()} bytes</small></button>`).join('')||'<p class="empty">Your workspace is ready. Create a note, or let an agent save a task result.</p>'}</div><p class="notice">Only this dedicated folder is shown. Agents can read its notes only with workspace access enabled.</p><div id="file-content"></div></div>`;root.querySelector('#new-note').onclick=()=>{dialog('New workspace note','<label>File name<input name="name" required maxlength="100" placeholder="My ideas.md"></label><label>Text<textarea name="content" rows="9" maxlength="60000" required></textarea></label>',async f=>{let name=f.elements.name.value.trim();if(!/\.[a-z0-9]+$/i.test(name))name+='.md';await api('workspace/create',{name,content:f.elements.content.value});context.toast('Note saved.')})};root.querySelectorAll('[data-read-file]').forEach(b=>b.onclick=()=>action(async()=>{const r=await api('workspace/read',{path:b.dataset.readFile});if(current!=='files'||!root.isConnected)return;root.querySelector('#file-content').innerHTML=`<h3 style="margin-top:25px">${esc(b.dataset.readFile)}</h3><div class="runtime-result">${esc(r.content)}</div>`}));}
  async function system(t){const s=await api('platform/status');if(!t.isConnected)return;t.innerHTML=`<h2>Lumen OS</h2><p class="muted">The future has a soul.</p><div class="runtime-grid"><div class="metric"><p>Memory available</p><strong>${bytes(s.memory.free)}</strong><p>${bytes(s.memory.total)} total</p></div><div class="metric"><p>Platform</p><strong>${esc(s.platform)}</strong><p>${esc(s.architecture)} · ${esc(s.release)}</p></div><div class="metric"><p>Service version</p><strong>${esc(s.version)}</strong><p>${esc(s.session)}</p></div></div><div class="setting-row"><div><h3>Processor</h3><p>${esc(s.cpu.model)} · ${s.cpu.threads} threads</p></div></div><div class="setting-row"><div><h3>Workspace storage</h3><p>${s.disk?bytes(s.disk.available)+' available':'Available after workspace initialization'}</p></div></div><div class="setting-row"><div><h3>Target minimum hardware</h3><p>8 GB RAM · Intel Core i5 · Integrated graphics. Dedicated graphics are optional. Hardware performance still needs measurement on a full Linux installation.</p></div></div><p class="notice">${s.platform==='linux'?'Running on Linux. Native apps open through the desktop service.':'Running as a Windows development preview. The source includes a Debian Linux session and ISO build recipe.'}</p>`;}
  async function apps(t,ctx){context=ctx;const s=await api('platform/status');if(!t.isConnected)return;const section=document.createElement('div');section.className='native-apps';section.innerHTML=`<h3>Linux applications</h3><div class="files-grid">${s.apps.map(a=>`<button class="file-tile" data-native="${a.id}" ${a.available?'':'disabled'}>${esc(a.name)}</button>`).join('')}</div><p class="runtime-note">${s.platform==='linux'?'Applications run with your normal Linux user permissions.':'Native launchers become available in the Linux desktop session.'}</p>`;t.querySelector('.page').append(section);section.querySelectorAll('[data-native]').forEach(b=>b.onclick=()=>action(async()=>{const r=await api('platform/launch',{id:b.dataset.native});context.toast(r.message)}))}
  async function poll(){clearTimeout(timer);if(!root?.isConnected||!['agents','automations'].includes(current))return;try{await reload();if(!root.isConnected)return;const jobs=root.querySelector('#runtime-jobs');if(jobs&&!document.querySelector('#runtime-editor')&&!jobs.querySelector('details[open]')){jobs.innerHTML=jobsHTML();bindJobs()}window.dispatchEvent(new CustomEvent('lumen-runtime',{detail:snapshot}))}catch{}timer=setTimeout(poll,3000)}
  async function render(section,target,ctx){clearTimeout(timer);context=ctx;root=target;current=section;target.innerHTML='<div class="page"><p class="muted" role="status">Opening your workspace…</p></div>';try{if(section==='files'){await files();return}await reload();if(!target.isConnected||current!==section)return;section==='agents'?agents():routines();timer=setTimeout(poll,3000)}catch(e){if(target.isConnected)target.innerHTML=`<div class="page"><h2>Workspace unavailable</h2><p class="runtime-error">${esc(e.message)}</p><p class="muted">Restart the local Lumen service, then reopen this panel.</p></div>`}}
  window.lumenRuntimeUI={render,system,apps,async newRoutine(){try{await reload();editRoutine()}catch(e){context.toast(e.message)}},stop(){clearTimeout(timer);current='';closeDialog()},get snapshot(){return snapshot}};
})();
