'use strict';
const crypto=require('node:crypto');
const {ApiError}=require('./providers.cjs');
const GOOGLE_SCOPE='https://www.googleapis.com/auth/gmail.readonly';
const GOOGLE_SIGN_IN_TIMEOUT_MS=10*60*1000;
const authUrl='https://accounts.google.com/o/oauth2/v2/auth',tokenUrl='https://oauth2.googleapis.com/token';
const clean=(v,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
const decode=value=>{try{return Buffer.from(String(value||'').replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')}catch{return''}};
function createConnectors({vault,fetcher=global.fetch,clock=()=>Date.now()}={}){
  if(!vault)throw new Error('A secure vault is required.');
  let pending=null;
  async function record(){return await vault.get('google-connector')||{}}
  async function status(){let r={},credentialError=null;try{r=await record()}catch{credentialError='Secure credential storage is locked or unavailable.'}const connected=!!r.refreshToken;return{
    google:{configured:!!r.clientId,connected,email:clean(r.email,200),scopes:connected?[GOOGLE_SCOPE]:[]},
    gmail:{connected,access:'Read-only',permission:'gmail.read'},
    credentialError,
    catalog:[
      {id:'google',name:'Google Account',category:'Accounts',state:connected?'connected':r.clientId?'ready':'setup'},
      {id:'gmail',name:'Gmail',category:'Communication',state:connected?'connected':'setup'},
      ...['Google Calendar','Google Drive','Google Sheets','Google Docs','Google Tasks','Google Photos','YouTube','Microsoft Outlook','OneDrive','GitHub','Notion','Slack','Trello'].map(name=>({id:name.toLowerCase().replace(/\W+/g,'-'),name,category:'Coming next',state:'planned'}))
    ]
  }}
  async function saveGoogle(input){const old=await record(),clientId=clean(input.clientId,300),clientSecret=clean(input.clientSecret,300)||old.clientSecret;if(!clientId||!clientId.endsWith('.apps.googleusercontent.com'))throw new ApiError('Enter a valid Google OAuth desktop client ID.',400);if(!clientSecret)throw new ApiError('Enter the client secret from the Google desktop app credential.',400);const changed=old.clientId&&old.clientId!==clientId;await vault.set('google-connector',{clientId,clientSecret,...(changed?{}:{refreshToken:old.refreshToken,accessToken:old.accessToken,expiresAt:old.expiresAt,email:old.email})});return{message:'Google OAuth app saved securely.'}}
  async function tokenRequest(params){const response=await fetcher(tokenUrl,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});let data={};try{data=await response.json()}catch{}if(!response.ok||!data.access_token)throw new ApiError('Google could not complete sign-in. Check the OAuth client and try again.',502);return data}
  async function accessToken(){const r=await record();if(!r.refreshToken)throw new ApiError('Connect Google Account in Integrations first.',409);if(r.accessToken&&Number(r.expiresAt)>clock()+60000)return r.accessToken;const data=await tokenRequest({client_id:r.clientId,client_secret:r.clientSecret,refresh_token:r.refreshToken,grant_type:'refresh_token'});await vault.set('google-connector',{...r,accessToken:data.access_token,expiresAt:clock()+Math.max(60,Number(data.expires_in)||3600)*1000});return data.access_token}
  async function gmail(path){const token=await accessToken(),response=await fetcher('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{headers:{authorization:'Bearer '+token}});let data={};try{data=await response.json()}catch{}if(response.status===401){const r=await record();await vault.set('google-connector',{...r,accessToken:null,expiresAt:0});throw new ApiError('Google authorization expired. Reconnect Google Account in Integrations.',401)}if(!response.ok)throw new ApiError(response.status===403?'Gmail access is unavailable. Enable the Gmail API for this Google project, then reconnect.':'Gmail could not be reached. Try again shortly.',response.status===403?409:502);return data}
  function textPart(payload){if(!payload)return'';if(payload.mimeType==='text/plain'&&payload.body?.data)return decode(payload.body.data);for(const part of payload.parts||[]){const found=textPart(part);if(found)return found}return''}
  async function listUnread({maxResults=8}={}){maxResults=Math.max(1,Math.min(10,Number(maxResults)||8));const list=await gmail('messages?labelIds=UNREAD&maxResults='+maxResults);const messages=[];for(const item of list.messages||[]){const m=await gmail('messages/'+encodeURIComponent(item.id)+'?format=full&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date'),headers=Object.fromEntries((m.payload?.headers||[]).map(h=>[String(h.name).toLowerCase(),clean(h.value,500)]));messages.push({id:m.id,threadId:m.threadId,from:headers.from||'',subject:headers.subject||'(No subject)',date:headers.date||'',snippet:clean(m.snippet,500),excerpt:clean(textPart(m.payload).replace(/\s+/g,' '),1800)})}return{messages,count:messages.length,resultSizeEstimate:Number(list.resultSizeEstimate)||messages.length}}
  async function testGmail(){const result=await listUnread({maxResults:3});return{message:`Gmail connected. ${result.resultSizeEstimate} unread message${result.resultSizeEstimate===1?'':'s'} found.`,messages:result.messages.map(({from,subject,date})=>({from,subject,date}))}}
  async function connectGoogle(redirectUri){if(pending)throw new ApiError('A Google sign-in is already waiting in your browser.',409);if(!/^http:\/\/127\.0\.0\.1:\d+\/api\/integrations\/google\/callback$/.test(redirectUri||''))throw new ApiError('The local Google callback is unavailable.',500);const r=await record();if(!r.clientId||!r.clientSecret)throw new ApiError('Configure the Google OAuth desktop app first.',409);const state=crypto.randomBytes(24).toString('base64url'),verifier=crypto.randomBytes(48).toString('base64url'),challenge=crypto.createHash('sha256').update(verifier).digest('base64url'),url=new URL(authUrl);for(const [k,v] of Object.entries({client_id:r.clientId,redirect_uri:redirectUri,response_type:'code',scope:GOOGLE_SCOPE,access_type:'offline',prompt:'consent',code_challenge:challenge,code_challenge_method:'S256',state}))url.searchParams.set(k,v);const timer=setTimeout(()=>{pending=null},GOOGLE_SIGN_IN_TIMEOUT_MS);timer.unref?.();pending={state,verifier,redirectUri,timer};return{url:url.toString(),expiresIn:GOOGLE_SIGN_IN_TIMEOUT_MS/1000}}
  async function completeGoogle({state,code}={}){const attempt=pending;if(!attempt||state!==attempt.state)throw new ApiError('Google sign-in expired. Return to Lumen and try again.',400);clearTimeout(attempt.timer);pending=null;if(!code)throw new ApiError('Google sign-in was cancelled.',400);const r=await record(),data=await tokenRequest({code,client_id:r.clientId,client_secret:r.clientSecret,redirect_uri:attempt.redirectUri,grant_type:'authorization_code',code_verifier:attempt.verifier}),profileResponse=await fetcher('https://gmail.googleapis.com/gmail/v1/users/me/profile',{headers:{authorization:'Bearer '+data.access_token}});let profile={};try{profile=await profileResponse.json()}catch{}await vault.set('google-connector',{...r,refreshToken:data.refresh_token||r.refreshToken,accessToken:data.access_token,expiresAt:clock()+Math.max(60,Number(data.expires_in)||3600)*1000,email:clean(profile.emailAddress,200)});return{email:clean(profile.emailAddress,200)}}
  async function disconnectGoogle(){if(pending){clearTimeout(pending.timer);pending=null}const r=await record();if(r.accessToken||r.refreshToken)fetcher('https://oauth2.googleapis.com/revoke?token='+encodeURIComponent(r.refreshToken||r.accessToken),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'}}).catch(()=>{});await vault.set('google-connector',r.clientId&&r.clientSecret?{clientId:r.clientId,clientSecret:r.clientSecret}:null);return{message:'Google Account disconnected.'}}
  function close(){if(pending){clearTimeout(pending.timer);pending=null}}
  return{status,saveGoogle,connectGoogle,completeGoogle,disconnectGoogle,listUnread,testGmail,close};
}
module.exports={createConnectors,GOOGLE_SCOPE};
