'use strict';
const fs=require('node:fs/promises'),path=require('node:path');
const {spawn}=require('node:child_process'),{createHash}=require('node:crypto');
// Secrets travel over stdin, never command arguments or browser storage.
function run(file,args,input=''){return new Promise((resolve,reject)=>{const c=spawn(file,args,{windowsHide:true,stdio:['pipe','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>{c.kill();reject(new Error('Credential store timed out.'))},15000);c.stdout.on('data',b=>out+=b);c.stderr.on('data',b=>err+=b);c.on('error',()=>{clearTimeout(timer);reject(new Error('System credential storage unavailable.'))});c.on('close',code=>{clearTimeout(timer);resolve({code,out:out.trim(),hasError:!!err.trim()})});c.stdin.on('error',()=>{});c.stdin.end(input)})}
async function dpapi(mode,text){const helper=path.join(__dirname,'windows-credential-helper.exe');const r=await run(helper,[mode.toLowerCase()],text);if(r.code!==0)throw new Error('Windows credential store unavailable.');return r.out}
function createVault(directory){const file=path.join(directory,'credentials.dpapi'),identity=createHash('sha256').update(path.resolve(directory)).digest('hex').slice(0,20);let cache=null,queue=Promise.resolve();
 async function load(){if(cache)return cache;if(process.platform==='win32'){let encoded;try{encoded=await fs.readFile(file,'utf8')}catch(e){if(e.code==='ENOENT')return cache={};throw e}cache=JSON.parse(Buffer.from(await dpapi('Unprotect',encoded),'base64').toString('utf8'))}else if(process.platform==='linux'){const r=await run('secret-tool',['lookup','application','lumen-os','instance',identity]);if(r.code!==0&&(r.code!==1||r.hasError))throw new Error('Unlock the Linux keyring.');cache=r.out?JSON.parse(r.out):{}}else throw new Error('Use Windows DPAPI or Linux Secret Service.');return cache}
 async function persist(next){const json=JSON.stringify(next);if(process.platform==='win32'){const encrypted=await dpapi('Protect',Buffer.from(json).toString('base64'));await fs.mkdir(directory,{recursive:true,mode:0o700});await fs.writeFile(file+'.tmp',encrypted,{mode:0o600});await fs.rename(file+'.tmp',file)}else if(process.platform==='linux'){const r=await run('secret-tool',['store','--label=Lumen OS API credentials','application','lumen-os','instance',identity],json);if(r.code!==0)throw new Error('Could not save to Linux keyring.')}else throw new Error('No secure storage available.');cache=next}
 return{kind:process.platform==='win32'?'Windows account encryption (DPAPI)':'Linux Secret Service keyring',async get(p){return(await load())[p]||null},async set(p,value){const task=queue.then(async()=>{const next={...await load()};if(value)next[p]=value;else delete next[p];await persist(next)});queue=task.catch(()=>{});return task},async status(){const v=await load();return Object.fromEntries(['openai','claude','gemini'].map(p=>[p,{saved:!!v[p]?.key,model:v[p]?.model||'',speechModel:v[p]?.speechModel||''}]))}};
}
module.exports={createVault};
