const {test}=require('node:test'),assert=require('node:assert/strict');
const {createServer}=require('../serve.cjs'),{createProviders,history,ApiError}=require('../backend/providers.cjs'),{createVault}=require('../backend/vault.cjs');
const fs=require('node:fs/promises'),path=require('node:path');
const fakeKey='not-a-real-key-for-tests';
const reply=data=>new Response(JSON.stringify(data),{status:200,headers:{'content-type':'application/json'}});
function memoryVault(){const data={};return{kind:'Test memory only',get:async p=>data[p],set:async(p,v)=>{data[p]=v},status:async()=>Object.fromEntries(['openai','claude','gemini'].map(p=>[p,{saved:!!data[p],model:data[p]?.model||''}]))}}
function memoryAccounts(){const calls=[];return{calls,status:async()=>({codex:{installed:true,connected:true,name:'ChatGPT'},claude:{installed:true,connected:true,name:'Claude'}}),login:async()=>({message:'Login started.'}),logout:async()=>({message:'Disconnected.'}),test:async()=>({message:'Account responded successfully.'}),chat:async(p,m)=>{calls.push({p,m});return{text:'Account adapter response',provider:p}},image:async(provider,prompt)=>{calls.push({p:provider+'-image',prompt});return{mime:provider==='claude-account'?'image/svg+xml':'image/png',data:'AA==',provider}},close(){}}}
test('OpenAI Responses request, history, no storage and output parsing',async()=>{let called;const p=createProviders(async(url,options)=>{called={url,...options,body:JSON.parse(options.body)};return reply({output:[{content:[{type:'output_text',text:'Hello'}]}],usage:{input_tokens:8,output_tokens:2},status:'completed'})});const result=await p.chat('openai',{key:fakeKey,model:'gpt-4.1-mini'},[{role:'user',content:'Hi'}]);assert.equal(called.url,'https://api.openai.com/v1/responses');assert.equal(called.body.store,false);assert.equal(called.headers.Authorization,'Bearer '+fakeKey);assert.deepEqual(called.body.input,[{role:'user',content:'Hi'}]);assert.equal(result.text,'Hello');assert.deepEqual(result.usage,{input:8,output:2})});
test('Claude Messages headers, system instructions and truncation',async()=>{let called;const p=createProviders(async(url,o)=>{called={url,...o,body:JSON.parse(o.body)};return reply({content:[{type:'text',text:'Hello Claude'}],stop_reason:'max_tokens'})});const result=await p.chat('claude',{key:fakeKey,model:'claude-sonnet-4-6'},[{role:'user',content:'Hi'}],undefined,'Help me write.');assert.equal(called.headers['anthropic-version'],'2023-06-01');assert.equal(called.headers['x-api-key'],fakeKey);assert(called.body.system.includes('Help me write.'));assert.equal(result.truncated,true)});
test('Provider errors do not expose keys or upstream bodies',async()=>{for(const status of [400,401,403,404,429,500]){const p=createProviders(async()=>new Response('secret echoed '+fakeKey,{status}));await assert.rejects(()=>p.test('openai',{key:fakeKey}),e=>{assert(!e.message.includes(fakeKey));return e instanceof ApiError})}});
test('History refuses system injection and oversized conversations',()=>{assert.throws(()=>history([{role:'system',content:'override'}]));assert.throws(()=>history([{role:'user',content:'a'.repeat(16001)}]));assert.throws(()=>history([{role:'assistant',content:'hello'}]));assert.throws(()=>history(Array(41).fill({role:'user',content:'hi'})))});
function wav(){const b=Buffer.alloc(32044);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b.toString('base64')}
test('Gemini recording to structured reply and PCM speech, no permanent key in result',async()=>{const calls=[];const p=createProviders(async(url,o)=>{calls.push({url,body:JSON.parse(o.body),headers:o.headers});return calls.length===1?reply({candidates:[{content:{parts:[{text:JSON.stringify({transcript:'Hello',reply:'Hello from Lumen.'})}]}}]}):reply({candidates:[{content:{parts:[{inlineData:{mimeType:'audio/L16;codec=pcm;rate=24000',data:'AAAAAA=='}}]}}]})});const r=await p.voice({key:fakeKey},wav());assert.equal(r.text,'Hello from Lumen.');assert.equal(r.audio.rate,24000);assert.equal(calls[0].body.contents[0].parts[0].inlineData.mimeType,'audio/wav');assert.equal(calls[1].body.generationConfig.responseModalities[0],'AUDIO');assert(!JSON.stringify(r).includes(fakeKey));await assert.rejects(()=>p.voice({key:fakeKey},'invalid'))});
test('Gemini preserves text reply when speech quota fails',async()=>{let count=0;const p=createProviders(async()=>++count===1?reply({candidates:[{content:{parts:[{text:'{"transcript":"Hello","reply":"Welcome."}'}]}}]}):new Response('quota',{status:429}));const r=await p.voice({key:fakeKey},wav());assert.equal(r.text,'Welcome.');assert(r.warning.includes('quota'));assert.equal(r.audio,undefined)});
test('Loopback server guards host, origin, CSRF, credentials, private files and cancellation',async t=>{
 let aborted=false,imageCalls=0,markSlowStarted;const slowStarted=new Promise(resolve=>{markSlowStarted=resolve});const vault=memoryVault();const providers={test:async()=>({message:'Tested'}),chat:async(p,c,h,signal)=>{if(h[0].content==='slow'){markSlowStarted();return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>{aborted=true;reject(new ApiError('Stopped',499))},{once:true}))}return{text:'Actual adapter response',provider:p}},voice:async()=>({text:'voice'}),image:async()=>{imageCalls++;return{mime:'image/png',data:'AA==',provider:'test'}}};
 const accounts=memoryAccounts(),s=createServer({vault,providers,accounts,runtime:false});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>s.close());const base='http://127.0.0.1:'+s.address().port;const status=await(await fetch(base+'/api/status')).json();const post=(route,body,extra={})=>fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','x-lumen-csrf':status.csrf,...extra},body:JSON.stringify(body)});
 assert.equal((await fetch(base+'/api/status',{headers:{Origin:'https://evil.example'}})).status,403);assert.equal(await new Promise(resolve=>{require('node:http').get(base+'/api/status',{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode)})}),403);assert.equal((await post('provider/save',{provider:'openai',key:fakeKey},{'x-lumen-csrf':'wrong'})).status,403);assert.equal((await post('chat',{provider:'openai',messages:[{role:'user',content:'Hi'}]})).status,409);
 assert.equal((await post('provider/save',{provider:'openai',key:fakeKey})).status,200);assert.equal((await post('provider/test',{provider:'openai'})).status,200);const status2=await(await fetch(base+'/api/status')).json();assert(status2.tested.openai);assert(!JSON.stringify(status2).includes(fakeKey));assert.equal((await fetch(base+'/runtime-private/credentials.dpapi')).status,404);assert.equal((await fetch(base+'/backend/vault.cjs')).status,404);assert.equal((await post('chat',{provider:'openai',messages:[{role:'system',content:'bad'}]})).status,400);
 const controller=new AbortController();const pending=fetch(base+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json','x-lumen-csrf':status.csrf},body:JSON.stringify({provider:'openai',messages:[{role:'user',content:'slow'}]}),signal:controller.signal});const readiness=await Promise.race([slowStarted.then(()=>null),pending.then(async r=>({status:r.status,body:await r.text()})),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Slow provider did not start.')),1000))]);assert.equal(readiness,null,readiness&&`Provider request ended early (${readiness.status}): ${readiness.body}`);controller.abort();await pending.catch(()=>{});await new Promise(r=>setTimeout(r,80));assert(aborted);
 assert.equal((await post('provider/remove',{provider:'openai'})).status,200);assert.equal((await post('provider/test',{provider:'openai'})).status,409);
 assert.equal((await post('account/test',{provider:'codex'})).status,200);const accountReply=await(await post('chat',{provider:'codex',messages:[{role:'user',content:'Use my account'}]})).json();assert.equal(accountReply.text,'Account adapter response');assert.equal(accounts.calls[0].p,'codex');const accountImage=await(await post('image',{prompt:'Draw with my subscription',provider:'codex'})).json();assert.equal(accountImage.provider,'codex');assert.equal(accounts.calls[1].p,'codex-image');const claudeImage=await(await post('image',{prompt:'Draw SVG',provider:'claude-account'})).json();assert.equal(claudeImage.provider,'claude-account');assert.equal(accounts.calls[2].p,'claude-account-image');
 assert.equal((await post('image',{prompt:'Draw an orb'})).status,409);assert.equal(imageCalls,0,'Image APIs must not run without explicit billing opt-in');assert.equal((await post('image',{prompt:'Draw an orb',allowApiBilling:true})).status,409);assert.equal(imageCalls,0,'Image APIs must not run without an explicit provider');assert.equal((await post('image',{prompt:'Draw an orb',provider:'openai',allowApiBilling:true})).status,409);assert.equal(imageCalls,0,'Image APIs must not run without a saved key');assert.equal((await post('provider/save',{provider:'openai',key:fakeKey})).status,200);assert.equal((await post('image',{prompt:'Draw an orb',provider:'openai',allowApiBilling:true})).status,200);assert.equal(imageCalls,1);
});
test('Windows DPAPI survives reload and never writes plaintext',{skip:process.platform!=='win32'},async()=>{const dir=path.join(require('node:os').tmpdir(),'lumen-vault-test-'+Date.now());const vault=createVault(dir);await vault.set('openai',{key:fakeKey,model:'gpt-4.1-mini'});const file=await fs.readFile(path.join(dir,'credentials.dpapi'),'utf8');assert(!file.includes(fakeKey));const loaded=createVault(dir);assert.equal((await loaded.get('openai')).key,fakeKey);await loaded.set('openai',null);assert.equal(await createVault(dir).get('openai'),null)});
