// Set PLAYWRIGHT_MODULE to an installed Playwright package path before running.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {createServer}=require('../serve.cjs');const assert=require('node:assert/strict');
(async()=>{
 const credentials={},calls=[],status=()=>Object.fromEntries(['openai','claude','gemini'].map(p=>[p,{saved:!!credentials[p],model:credentials[p]?.model||''}]));
 const vault={kind:'Test memory vault',get:async p=>credentials[p],set:async(p,v)=>credentials[p]=v,status:async()=>status()};
 const audio={pcm:Buffer.alloc(9600).toString('base64'),rate:24000};
 const providers={test:async(p)=>({message:p+' model responded.'}),chat:async(p,c,m,signal,instructions)=>{calls.push({p,m,instructions});if(m.at(-1).content==='slow')return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new Error('Cancelled'))));if(m.at(-1).content==='make image')return{text:'IMAGE: a violet orb',provider:p};return{text:'A real response path with '+p,provider:p,usage:{input:10,output:6}}},image:async()=>({mime:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',provider:'openai'}),speech:async()=>audio,voice:async(c,wav)=>{assert(Buffer.from(wav,'base64').toString('ascii',0,4)==='RIFF');calls.push({voice:true});return{transcript:'Hello Lumen',text:'Hello. Voice route works.',audio,provider:'gemini'}}};
 const accounts={status:async()=>({codex:{installed:true,connected:true,name:'ChatGPT'},claude:{installed:false,connected:false,name:'Claude'}}),login:async()=>({message:'Login started.'}),logout:async()=>({message:'Disconnected.'}),test:async()=>({message:'Account responded successfully.'}),chat:async(p,m,s,instructions)=>{calls.push({account:p,m,instructions});return{text:'Account response',provider:p}},close(){}};
 const directory=await require('node:fs/promises').mkdtemp(require('node:path').join(require('node:os').tmpdir(),'lumen-browser-'));const server=createServer({vault,providers,accounts,directory});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required']});
 try{
 const context=await browser.newContext({viewport:{width:1440,height:950},permissions:['microphone']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('[data-account=codex]').waitFor();assert(await page.locator('[data-account=codex]').getByText('Subscription account connected',{exact:true}).isVisible());assert(await page.locator('[data-account=claude]').getByText('Runtime required',{exact:true}).isVisible());const openai=page.locator('[data-provider=openai]');await openai.getByLabel('API key',{exact:true}).fill('dummy-test-key-not-real');await openai.getByRole('button',{name:'Save securely'}).click();await openai.getByText('Credential saved securely.',{exact:false}).waitFor();assert.equal(await openai.getByLabel('API key',{exact:true}).inputValue(),'');await openai.getByRole('button',{name:'Test connection',exact:true}).click();await openai.getByText('openai model responded.').waitFor();await page.locator('#provider-preference').selectOption('OpenAI');await page.locator('#image-provider').selectOption('openai');await page.getByRole('button',{name:'Save preferences',exact:true}).click();assert(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes('dummy-test-key'));
 await page.getByRole('button',{name:'Conversation',exact:true}).click();await page.getByRole('textbox',{name:'Message Lumen'}).fill('Hi');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('A real response path with openai',{exact:false}).waitFor();assert.equal(calls[0].m.at(-1).content,'Hi');await page.getByRole('textbox',{name:'Message Lumen'}).fill('make image');await page.getByRole('button',{name:'Send message',exact:true}).click();const generated=page.getByRole('button',{name:'Open generated image full screen'});await generated.waitFor();await generated.click();await page.locator('#image-viewer[open]').waitFor();await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#image-viewer').open);
 await page.getByRole('textbox',{name:'Message Lumen'}).fill('slow');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByRole('button',{name:'Stop request',exact:true}).click();await page.locator('.message').filter({hasText:'Request stopped.'}).waitFor();
 await page.getByRole('button',{name:'Agents',exact:true}).click();await page.getByRole('button',{name:'Start chat'}).first().click();await page.getByRole('textbox',{name:'Message Lumen'}).fill('Help with research');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('Account response',{exact:false}).waitFor();assert(calls.at(-1).instructions.includes('Help investigate'));
 await page.getByRole('button',{name:'Automations',exact:true}).click();await page.getByRole('button',{name:'New automation',exact:false}).click();const routineEditor=page.locator('#runtime-editor');await routineEditor.getByLabel('Agent for this automation',{exact:true}).selectOption('research');await routineEditor.getByLabel('Name',{exact:true}).fill('Morning review');await routineEditor.getByLabel('Task',{exact:true}).fill('Prepare today’s priorities.');await routineEditor.getByRole('button',{name:'Save',exact:true}).click();const automationAgent=page.getByLabel('Agent for Morning review',{exact:true});await automationAgent.waitFor();assert.equal(await automationAgent.inputValue(),'research');await automationAgent.selectOption('workspace');await page.getByText('Automation agent updated.',{exact:true}).waitFor();assert.equal(await page.getByLabel('Agent for Morning review',{exact:true}).inputValue(),'workspace');
 await page.getByRole('button',{name:'Settings',exact:true}).click();const gemini=page.locator('[data-provider=gemini]');await gemini.getByLabel('API key',{exact:true}).fill('dummy-gemini-key-not-real');await gemini.getByRole('button',{name:'Save securely'}).click();await gemini.getByText('Credential saved securely.',{exact:false}).waitFor();await gemini.getByRole('button',{name:'Test voice',exact:true}).click();await gemini.getByText('Speech output played successfully.').waitFor();
 await page.getByRole('button',{name:'Close window',exact:true}).click();const mic=page.getByRole('button',{name:'Talk to Gemini',exact:true});await mic.hover();await page.mouse.down();await page.getByText('Recording · release to send',{exact:true}).waitFor();await page.waitForTimeout(850);await page.mouse.up();await page.waitForFunction(()=>!document.querySelector('#voice-bar').hidden&&document.querySelector('#voice-status').textContent.includes('speaking'));await page.waitForFunction(()=>document.querySelector('#voice-bar').hidden);assert(calls.some(c=>c.voice));
 await page.getByRole('button',{name:'Conversation',exact:true}).click();await page.locator('.message').filter({hasText:'Hello. Voice route works.'}).waitFor();
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('[data-provider=openai]').getByRole('button',{name:'Remove key'}).click();await page.getByText('Saved credential removed.',{exact:true}).waitFor();assert.equal(credentials.openai,null);
 await page.setViewportSize({width:375,height:812});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:require('node:path').join(directory,'mobile.png')});
 assert.deepEqual(errors,[]);console.log('PASS: save/test/remove keys, no browser credential storage, live chat path, cancellation, agent instructions, speech playback, fake microphone capture + voice reply, mobile overflow, no runtime errors. All provider calls were mocked.');
 }finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});


