'use strict';
// This suite uses real local persistence with simulated model providers and a fake offline download.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {createServer}=require('../serve.cjs');
(async()=>{
  const directory=await fs.mkdtemp(path.join(require('node:os').tmpdir(),'lumen-desktop-'));
  const vault={kind:'Test vault',get:async()=>({key:'fake-credential',model:'test'}),status:async()=>({openai:{saved:true},claude:{saved:true}})};
  const calls=[];const providers={chat:async(p,c,m,s,i)=>{calls.push({p,m,i});return{text:'A thoughtful plan from your notes.',provider:p,usage:{input:10,output:8}}}};
  let installed=false,download=null,engineStarted=false;
  const offline={status:async()=>({available:engineStarted,models:installed?[{name:'qwen2.5:1.5b'}]:[],catalog:[{id:'qwen2.5:1.5b',name:'Qwen test',description:'Test model',size:'1 GB'}]}),pull:()=>{download={id:'d1',model:'qwen2.5:1.5b',status:'completed'};installed=true;return download},downloads:()=>download?[download]:[],chat:async()=>({text:'This reply stayed local.',provider:'offline'}),close(){}};
  const accounts={status:async()=>({codex:{installed:false,connected:false},claude:{installed:false,connected:false}}),close(){}};
  const platform={...require('../backend/platform.cjs').createPlatform({directory}),offlineEngine:async()=>({bundled:true}),startOffline:async()=>{engineStarted=true;return{message:'Started'}}};const server=createServer({directory,vault,providers,offline,platform,accounts});await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const base='http://127.0.0.1:'+server.address().port,b=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'msedge',headless:true});
  try{
    const page=await b.newPage({viewport:{width:1440,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let denied=false;await page.route('**/api/workspace/create',route=>{if(!denied){denied=true;return route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({code:'SESSION_EXPIRED',error:'Session expired'})})}return route.continue()});await page.goto(base);
    await page.getByRole('button',{name:'Files',exact:true}).click();await page.getByRole('button',{name:'New note',exact:false}).click();let d=page.locator('#runtime-editor');await d.getByLabel('File name').fill('ideas.md');await d.getByLabel('Text',{exact:true}).fill('My goal is a calm workspace. <script>alert(1)</script>');await d.getByRole('button',{name:'Save',exact:true}).click();await page.locator('[data-read-file="ideas.md"]').click();await page.getByText('My goal is a calm workspace. <script>alert(1)</script>',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Agents',exact:true}).click();await page.getByRole('button',{name:'New agent',exact:false}).click();d=page.locator('#runtime-editor');await d.getByLabel('Name',{exact:true}).fill('Writer <safe>');await d.getByLabel('Purpose and instructions').fill('Help me draft a simple plan.');await d.getByLabel('Text provider').selectOption('openai');await d.locator('[value="workspace.read"]').check();await d.locator('[value="notes.write"]').check();await d.getByRole('button',{name:'Save',exact:true}).click();const card=page.locator('.card').filter({has:page.getByRole('heading',{name:'Writer <safe>',exact:true})});await card.getByRole('button',{name:'Run task',exact:true}).click();d=page.locator('#runtime-editor');await d.getByLabel('What should this agent do?').fill('Read my notes and draft a plan.');await d.getByRole('button',{name:'Run task',exact:true}).click();await page.locator('.job .badge').filter({hasText:'completed'}).first().waitFor();await page.getByText('Read result',{exact:true}).first().click();await page.getByText('A thoughtful plan from your notes.',{exact:true}).waitFor();assert(calls[0].m[0].content.includes('My goal is a calm workspace.'));await page.getByLabel('Reply to Writer <safe>',{exact:true}).fill('Turn this into three concrete steps.');await page.getByRole('button',{name:'Send to agent',exact:true}).click();await page.locator('.job .badge').filter({hasText:'completed'}).nth(1).waitFor();assert(calls[1].m[0].content.includes('Turn this into three concrete steps.'));assert(calls[1].m[0].content.includes('A thoughtful plan from your notes.'));
    await page.getByRole('button',{name:'Automations',exact:true}).click();await page.getByRole('button',{name:'New automation',exact:false}).click();d=page.locator('#runtime-editor');await d.getByLabel('Name',{exact:true}).fill('Morning ideas');await d.getByLabel('Task',{exact:true}).fill('Review my notes.');await d.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('heading',{name:'Morning ideas',exact:true}).waitFor();assert.equal(await page.locator('[data-toggle-routine]').getAttribute('aria-checked'),'false');await page.locator('#scheduler-form [name=enabled]').check();await page.locator('#scheduler-form [name=budget]').fill('5');await page.getByRole('button',{name:'Save scheduler',exact:true}).click();await page.getByText('The scheduler is on.',{exact:false}).waitFor();
    await page.reload();await page.getByRole('button',{name:'Automations',exact:true}).click();await page.getByRole('heading',{name:'Morning ideas',exact:true}).waitFor();assert(await page.locator('#scheduler-form [name=enabled]').isChecked());assert.equal(calls.length,2,'Paused automation must not call provider');
    await page.getByRole('button',{name:'Settings',exact:true}).click();assert.equal(engineStarted,false);await page.getByRole('button',{name:'Start local engine',exact:true}).click();await page.getByRole('button',{name:'Download model',exact:true}).click();await page.locator('#offline-settings #offline-refresh').click();await page.locator('#offline-model').selectOption('qwen2.5:1.5b');await page.getByRole('button',{name:'Use this offline model'}).click();await page.getByRole('button',{name:'Conversation',exact:true}).click();await page.getByLabel('Message Lumen',{exact:true}).fill('Hello');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('This reply stayed local.',{exact:false}).waitFor();assert.equal(calls.length,2);
    await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('[data-setting=system]').click();await page.getByText('Memory available',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Close window',exact:true}).click();await page.setViewportSize({width:1366,height:768});const cap=await page.locator('.home-content .demo-caption').last().boundingBox();assert(cap.y+cap.height<=768,'Desktop caption should fit a 768px display');
    await page.setViewportSize({width:375,height:812});await page.getByRole('button',{name:'Agents',exact:true}).click();await page.locator('.cards').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(directory,'mobile.png')});
    assert.deepEqual(errors,[]);console.log('PASS: real notes, escaped content, permission-granted agent jobs with contextual replies, persisted paused routines and scheduler settings, local-only offline chat, responsive layout, no browser errors. Model calls were simulated.');
  }finally{await b.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exit(1)});
